[package]
name = "ttml"
version = "0.7.0"
authors = ["Thomas Lackemann <tommylackemann@gmail.com>"]

[lib]
# crate-type = ["cdylib"]

[dependencies]
nom = "^4.0.0-alpha1"
serde = "1.0.16"
serde_derive = "1.0.16"
serde_json = "1.0.4"
